export type ThemeCategory = "light" | "dark" | "amoled";

export interface ThemeColors {
  canvas: string;
  surface: string;
  wash: string;
  text: string;
  muted: string;
  border: string;
  frame: string;
  frameSurface: string;
  frameText: string;
  frameMuted: string;
  accent: string;
  frameAccent: string;
  onAccent: string;
  chart: readonly [string, string, string, string];
}

export interface ThemeDef {
  id: string;
  name: string;
  category: ThemeCategory;
  tone: {
    id: string;
    en: string;
  };
  colors: ThemeColors;
}

export interface ThemeSemanticColors {
  success: string;
  danger: string;
  warning: string;
  frameSuccess: string;
  frameDanger: string;
  frameWarning: string;
}

export const DEFAULT_THEME_ID = "slate-stone";

export const themeSemanticColors: Record<ThemeCategory, ThemeSemanticColors> = {
  light: {
    success: "#21654C",
    danger: "#9D3F3C",
    warning: "#745A18",
    frameSuccess: "#72C99F",
    frameDanger: "#F18982",
    frameWarning: "#E4BF68",
  },
  dark: {
    success: "#73CCA4",
    danger: "#F28B84",
    warning: "#E3C26C",
    frameSuccess: "#73CCA4",
    frameDanger: "#F28B84",
    frameWarning: "#E3C26C",
  },
  amoled: {
    success: "#67D8A0",
    danger: "#FF8B82",
    warning: "#FFD06A",
    frameSuccess: "#67D8A0",
    frameDanger: "#FF8B82",
    frameWarning: "#FFD06A",
  },
};

export const themes: ThemeDef[] = [
  {
    id: "sepia-paper",
    name: "Sepia Paper",
    category: "light",
    tone: { id: "Amber & mahoni", en: "Amber & mahogany" },
    colors: {
      canvas: "#F2E9D9",
      surface: "#FFFAF0",
      wash: "#E7D3B4",
      text: "#2A2018",
      muted: "#65513D",
      border: "#B7A184",
      frame: "#241710",
      frameSurface: "#39251A",
      frameText: "#FCF2E4",
      frameMuted: "#D8BE9C",
      accent: "#6F3F18",
      frameAccent: "#F0B765",
      onAccent: "#FFF7EA",
      chart: ["#6F3F18", "#2F6A58", "#4F5F8F", "#9B3F4B"],
    },
  },
  {
    id: "nordic-light",
    name: "Nordic Light",
    category: "light",
    tone: { id: "Es & kobalt", en: "Ice & cobalt" },
    colors: {
      canvas: "#E9F1F8",
      surface: "#FBFDFF",
      wash: "#D5E5F3",
      text: "#12263B",
      muted: "#45627C",
      border: "#93ACC1",
      frame: "#0C2238",
      frameSurface: "#123553",
      frameText: "#F2F8FD",
      frameMuted: "#B3D1E7",
      accent: "#1555A5",
      frameAccent: "#75BCFF",
      onAccent: "#F8FCFF",
      chart: ["#1555A5", "#007A72", "#6C4C9B", "#A24839"],
    },
  },
  {
    id: "matcha-latte",
    name: "Matcha Latte",
    category: "light",
    tone: { id: "Matcha & pinus", en: "Matcha & pine" },
    colors: {
      canvas: "#EAF0DF",
      surface: "#F9FBEF",
      wash: "#D3DFBF",
      text: "#1D2D1F",
      muted: "#50644E",
      border: "#9FAE91",
      frame: "#132418",
      frameSurface: "#1D3823",
      frameText: "#F0F7E8",
      frameMuted: "#BCD2B8",
      accent: "#2F6838",
      frameAccent: "#A8D86F",
      onAccent: "#F7FBEF",
      chart: ["#2F6838", "#7A5B14", "#3F658D", "#854558"],
    },
  },
  {
    id: "rose-quartz",
    name: "Rose Quartz",
    category: "light",
    tone: { id: "Mawar & burgundi", en: "Rose & burgundy" },
    colors: {
      canvas: "#F8E8ED",
      surface: "#FFF8FA",
      wash: "#EDC9D4",
      text: "#361B24",
      muted: "#704756",
      border: "#C59AA8",
      frame: "#2B101C",
      frameSurface: "#451829",
      frameText: "#FFF0F5",
      frameMuted: "#E4AFBF",
      accent: "#8F2F50",
      frameAccent: "#FF9FBE",
      onAccent: "#FFF8FA",
      chart: ["#8F2F50", "#316C7A", "#58713B", "#73509B"],
    },
  },
  {
    id: "soft-sand",
    name: "Soft Sand",
    category: "light",
    tone: { id: "Pasir & terakota", en: "Sand & terracotta" },
    colors: {
      canvas: "#F3E8DA",
      surface: "#FFFAF4",
      wash: "#E6CDB1",
      text: "#302219",
      muted: "#6C503C",
      border: "#BFA184",
      frame: "#28170E",
      frameSurface: "#43281A",
      frameText: "#FFF1E5",
      frameMuted: "#DCB89D",
      accent: "#8A3F20",
      frameAccent: "#F2A36E",
      onAccent: "#FFF9F4",
      chart: ["#8A3F20", "#2E706C", "#455F92", "#75517F"],
    },
  },
  {
    id: "cloudy-day",
    name: "Cloudy Day",
    category: "light",
    tone: { id: "Kabut & biru baja", en: "Mist & steel blue" },
    colors: {
      canvas: "#E8EEF1",
      surface: "#FBFDFE",
      wash: "#CCDCE3",
      text: "#1A2B34",
      muted: "#465F6A",
      border: "#95ADB7",
      frame: "#122832",
      frameSurface: "#1A3D49",
      frameText: "#F1F8FA",
      frameMuted: "#B5D0D8",
      accent: "#285E72",
      frameAccent: "#78C6D8",
      onAccent: "#FBFEFF",
      chart: ["#285E72", "#716019", "#67488A", "#A2433B"],
    },
  },
  {
    id: "lavender-mist",
    name: "Lavender Mist",
    category: "light",
    tone: { id: "Lavender & iris", en: "Lavender & iris" },
    colors: {
      canvas: "#F0E8F8",
      surface: "#FCF8FF",
      wash: "#DDCAE9",
      text: "#2B183A",
      muted: "#665075",
      border: "#B5A0C5",
      frame: "#24102F",
      frameSurface: "#3B184E",
      frameText: "#F9EEFF",
      frameMuted: "#D1B1DE",
      accent: "#6E348C",
      frameAccent: "#D59AF2",
      onAccent: "#FDF8FF",
      chart: ["#6E348C", "#16736F", "#94502E", "#4D6C36"],
    },
  },
  {
    id: "vanilla-cream",
    name: "Vanilla Cream",
    category: "light",
    tone: { id: "Vanila & mustard", en: "Vanilla & mustard" },
    colors: {
      canvas: "#F8EED2",
      surface: "#FFFAF0",
      wash: "#EAD79F",
      text: "#33280D",
      muted: "#6B5B2F",
      border: "#BCAE7E",
      frame: "#2A2109",
      frameSurface: "#47370C",
      frameText: "#FFF4CE",
      frameMuted: "#DDCB8D",
      accent: "#745500",
      frameAccent: "#F1C94E",
      onAccent: "#FFFAEF",
      chart: ["#745500", "#2F6D50", "#3F5F98", "#8C3E4D"],
    },
  },
  {
    id: "sage-garden",
    name: "Sage Garden",
    category: "light",
    tone: { id: "Sage & hutan", en: "Sage & forest" },
    colors: {
      canvas: "#E5EFE7",
      surface: "#F7FBF7",
      wash: "#C9DEC9",
      text: "#1E3023",
      muted: "#465E4D",
      border: "#95AD9C",
      frame: "#13271A",
      frameSurface: "#1E3D28",
      frameText: "#EFF9F1",
      frameMuted: "#B3D1BA",
      accent: "#35633D",
      frameAccent: "#92D3A0",
      onAccent: "#F6FBF6",
      chart: ["#35633D", "#8B5B19", "#41638C", "#8C4054"],
    },
  },
  {
    id: "oatmeal",
    name: "Oatmeal",
    category: "light",
    tone: { id: "Linen & taupe", en: "Linen & taupe" },
    colors: {
      canvas: "#EEE9E1",
      surface: "#FAF8F4",
      wash: "#DAD0C3",
      text: "#292824",
      muted: "#5D5A54",
      border: "#A9A198",
      frame: "#1E1D1A",
      frameSurface: "#34312C",
      frameText: "#F6F2EC",
      frameMuted: "#C9C2B9",
      accent: "#55493A",
      frameAccent: "#D0B78F",
      onAccent: "#FBF8F3",
      chart: ["#55493A", "#2D6B63", "#5C5389", "#8A453D"],
    },
  },
  {
    id: "slate-stone",
    name: "Kinpaku Slate",
    category: "light",
    tone: { id: "Kertas & emas", en: "Paper & gold" },
    colors: {
      canvas: "#F3EEE3",
      surface: "#FBF7ED",
      wash: "#DDD3BE",
      text: "#161713",
      muted: "#595B52",
      border: "#ADA796",
      frame: "#10120F",
      frameSurface: "#1D211A",
      frameText: "#F3EFE6",
      frameMuted: "#C2BDB2",
      accent: "#765519",
      frameAccent: "#D7B669",
      onAccent: "#FFF9EA",
      chart: ["#765519", "#2E6B55", "#4C648A", "#9A4944"],
    },
  },
  {
    id: "dracula-soft",
    name: "Dracula Soft",
    category: "dark",
    tone: { id: "Plum & fuchsia", en: "Plum & fuchsia" },
    colors: {
      canvas: "#18131F",
      surface: "#241A2E",
      wash: "#33213F",
      text: "#F8EFFB",
      muted: "#C9B4D1",
      border: "#5B406B",
      frame: "#0D0912",
      frameSurface: "#21122B",
      frameText: "#FCF3FF",
      frameMuted: "#D8BFE2",
      accent: "#FF93C9",
      frameAccent: "#EAB0FF",
      onAccent: "#2A0E20",
      chart: ["#FF93C9", "#65D6CB", "#F2C06B", "#8FB2FF"],
    },
  },
  {
    id: "deep-ocean",
    name: "Deep Ocean",
    category: "dark",
    tone: { id: "Navy & cyan", en: "Navy & cyan" },
    colors: {
      canvas: "#071B27",
      surface: "#0D2A39",
      wash: "#123B4D",
      text: "#ECFBFF",
      muted: "#AAD2DD",
      border: "#376979",
      frame: "#031017",
      frameSurface: "#092A38",
      frameText: "#EDFCFF",
      frameMuted: "#ACD9E5",
      accent: "#5FD7F2",
      frameAccent: "#88E6FF",
      onAccent: "#06212A",
      chart: ["#5FD7F2", "#6DDBA7", "#FFC76B", "#C99BFF"],
    },
  },
  {
    id: "charcoal-mist",
    name: "Charcoal Mist",
    category: "dark",
    tone: { id: "Grafit & jingga", en: "Graphite & orange" },
    colors: {
      canvas: "#191817",
      surface: "#282522",
      wash: "#3B322B",
      text: "#F7F3EE",
      muted: "#C7BCB2",
      border: "#62574D",
      frame: "#0E0D0C",
      frameSurface: "#282019",
      frameText: "#FCF7F2",
      frameMuted: "#D4C2B1",
      accent: "#FFAD72",
      frameAccent: "#FFC18E",
      onAccent: "#2C1405",
      chart: ["#FFAD72", "#75C9B4", "#8DAEFF", "#E595B4"],
    },
  },
  {
    id: "forest-night",
    name: "Forest Night",
    category: "dark",
    tone: { id: "Hutan & lime", en: "Forest & lime" },
    colors: {
      canvas: "#0A1A12",
      surface: "#10291C",
      wash: "#183C28",
      text: "#EEF9F1",
      muted: "#B1D0BA",
      border: "#356748",
      frame: "#05100A",
      frameSurface: "#0F2B1B",
      frameText: "#F1FAF4",
      frameMuted: "#B6D7C0",
      accent: "#A8D96F",
      frameAccent: "#C3ED8F",
      onAccent: "#142306",
      chart: ["#A8D96F", "#5DCEE0", "#E0A0D2", "#FFB36B"],
    },
  },
  {
    id: "evergreen",
    name: "Evergreen",
    category: "dark",
    tone: { id: "Pinus & emas", en: "Pine & gold" },
    colors: {
      canvas: "#111A16",
      surface: "#1C2922",
      wash: "#2A392E",
      text: "#F7F3E8",
      muted: "#C7C1AE",
      border: "#5B6251",
      frame: "#09100C",
      frameSurface: "#1A2B20",
      frameText: "#FBF7EA",
      frameMuted: "#D0C9B3",
      accent: "#E4BF67",
      frameAccent: "#F1D17D",
      onAccent: "#261C03",
      chart: ["#E4BF67", "#66C9A1", "#7FAEE9", "#E58E84"],
    },
  },
  {
    id: "midnight-blue",
    name: "Midnight Blue",
    category: "dark",
    tone: { id: "Indigo & periwinkle", en: "Indigo & periwinkle" },
    colors: {
      canvas: "#0C1330",
      surface: "#151F46",
      wash: "#202D5B",
      text: "#F3F5FF",
      muted: "#B8C1E2",
      border: "#48588E",
      frame: "#05091C",
      frameSurface: "#121C43",
      frameText: "#F5F6FF",
      frameMuted: "#C4CCED",
      accent: "#9EB5FF",
      frameAccent: "#BBC9FF",
      onAccent: "#101A42",
      chart: ["#9EB5FF", "#62D0BC", "#FF9DC7", "#F2C66F"],
    },
  },
  {
    id: "chocolate-dark",
    name: "Chocolate Dark",
    category: "dark",
    tone: { id: "Kakao & karamel", en: "Cocoa & caramel" },
    colors: {
      canvas: "#1C0F0A",
      surface: "#2C1911",
      wash: "#442417",
      text: "#FFF4EB",
      muted: "#D7B9A5",
      border: "#76513F",
      frame: "#0F0705",
      frameSurface: "#2A160E",
      frameText: "#FFF7F0",
      frameMuted: "#E2C2AD",
      accent: "#F1A66F",
      frameAccent: "#F7BB8E",
      onAccent: "#301307",
      chart: ["#F1A66F", "#6ECBB2", "#AFA4FF", "#EA8FA3"],
    },
  },
  {
    id: "nord-night",
    name: "Nord Night",
    category: "dark",
    tone: { id: "Biru arang & es", en: "Blue charcoal & ice" },
    colors: {
      canvas: "#151D28",
      surface: "#202C3A",
      wash: "#2C3C4F",
      text: "#F2F7FB",
      muted: "#B9C8D4",
      border: "#50677A",
      frame: "#0B1119",
      frameSurface: "#182633",
      frameText: "#F4F8FC",
      frameMuted: "#C2D1DC",
      accent: "#8FC8F0",
      frameAccent: "#ACD9F8",
      onAccent: "#10293A",
      chart: ["#8FC8F0", "#8DD1B2", "#F1B67E", "#C3A2E3"],
    },
  },
  {
    id: "shadow-grey",
    name: "Shadow Grey",
    category: "dark",
    tone: { id: "Monokrom & perak", en: "Monochrome & silver" },
    colors: {
      canvas: "#151515",
      surface: "#242424",
      wash: "#343434",
      text: "#F5F5F3",
      muted: "#BFBFBA",
      border: "#5A5A56",
      frame: "#080808",
      frameSurface: "#1D1D1C",
      frameText: "#F8F8F5",
      frameMuted: "#C9C9C3",
      accent: "#E8E8E1",
      frameAccent: "#F2F2EC",
      onAccent: "#1B1B1A",
      chart: ["#E8E8E1", "#82C2AE", "#D5A0B5", "#C6AD75"],
    },
  },
  {
    id: "amoled-cyber",
    name: "AMOLED Sapphire",
    category: "amoled",
    tone: { id: "Hitam & sapphire", en: "Black & sapphire" },
    colors: {
      canvas: "#000000",
      surface: "#07101F",
      wash: "#0B1D38",
      text: "#F2F7FF",
      muted: "#AEC8E8",
      border: "#244F86",
      frame: "#000000",
      frameSurface: "#06142A",
      frameText: "#F5F9FF",
      frameMuted: "#B7D2F2",
      accent: "#66A9FF",
      frameAccent: "#8BC0FF",
      onAccent: "#03152E",
      chart: ["#66A9FF", "#51D8CA", "#D6A1FF", "#FFC66E"],
    },
  },
  {
    id: "pitch-black-mint",
    name: "Pitch Black Mint",
    category: "amoled",
    tone: { id: "Hitam & mint", en: "Black & mint" },
    colors: {
      canvas: "#000000",
      surface: "#06130E",
      wash: "#0A2419",
      text: "#EFFBF5",
      muted: "#A8D3BB",
      border: "#225C43",
      frame: "#000000",
      frameSurface: "#071A12",
      frameText: "#F2FCF7",
      frameMuted: "#B2DCC4",
      accent: "#55E39B",
      frameAccent: "#7AF0B3",
      onAccent: "#031A0F",
      chart: ["#55E39B", "#71B4FF", "#FF9DB7", "#E7C365"],
    },
  },
  {
    id: "true-obsidian",
    name: "True Obsidian",
    category: "amoled",
    tone: { id: "Hitam & lava", en: "Black & lava" },
    colors: {
      canvas: "#000000",
      surface: "#110907",
      wash: "#25110B",
      text: "#FFF3EC",
      muted: "#D4B3A2",
      border: "#643120",
      frame: "#000000",
      frameSurface: "#170B07",
      frameText: "#FFF6F1",
      frameMuted: "#E0BEAC",
      accent: "#FF8D5C",
      frameAccent: "#FFA77F",
      onAccent: "#2A0B02",
      chart: ["#FF8D5C", "#65D4B2", "#8EAFFF", "#DB9DEA"],
    },
  },
  {
    id: "midnight-gold",
    name: "Midnight Gold",
    category: "amoled",
    tone: { id: "Hitam & emas", en: "Black & gold" },
    colors: {
      canvas: "#000000",
      surface: "#120D03",
      wash: "#2A1F07",
      text: "#FFF7E6",
      muted: "#DBC795",
      border: "#6D551C",
      frame: "#000000",
      frameSurface: "#181104",
      frameText: "#FFF9EA",
      frameMuted: "#E3CF9D",
      accent: "#F3C653",
      frameAccent: "#FFDA74",
      onAccent: "#2B2003",
      chart: ["#F3C653", "#63D0AA", "#75B4FF", "#E78DA4"],
    },
  },
  {
    id: "eink-slate",
    name: "Eink Slate",
    category: "amoled",
    tone: { id: "Hitam & sage pucat", en: "Black & pale sage" },
    colors: {
      canvas: "#000000",
      surface: "#0C100E",
      wash: "#17221C",
      text: "#F1F5F2",
      muted: "#B7C8BE",
      border: "#415B4D",
      frame: "#000000",
      frameSurface: "#0F1713",
      frameText: "#F5F8F6",
      frameMuted: "#C1D1C7",
      accent: "#B8D6C3",
      frameAccent: "#D1E7D8",
      onAccent: "#15231A",
      chart: ["#B8D6C3", "#95AFD8", "#C2A4CA", "#D2B38D"],
    },
  },
  {
    id: "cosmic-dusk",
    name: "Cosmic Dusk",
    category: "amoled",
    tone: { id: "Hitam & violet", en: "Black & violet" },
    colors: {
      canvas: "#000000",
      surface: "#100718",
      wash: "#251039",
      text: "#FAF2FF",
      muted: "#CDB3DE",
      border: "#5B377B",
      frame: "#000000",
      frameSurface: "#170A22",
      frameText: "#FCF5FF",
      frameMuted: "#D7BDE6",
      accent: "#C08BFF",
      frameAccent: "#D2A7FF",
      onAccent: "#24103A",
      chart: ["#C08BFF", "#55D6C5", "#FF95B2", "#F0C260"],
    },
  },
  {
    id: "black-coral",
    name: "Black Coral",
    category: "amoled",
    tone: { id: "Hitam & coral", en: "Black & coral" },
    colors: {
      canvas: "#000000",
      surface: "#150704",
      wash: "#301008",
      text: "#FFF4EF",
      muted: "#DAB5A5",
      border: "#73331F",
      frame: "#000000",
      frameSurface: "#1D0804",
      frameText: "#FFF7F3",
      frameMuted: "#E2BDAC",
      accent: "#FF835F",
      frameAccent: "#FF9F82",
      onAccent: "#2E0C03",
      chart: ["#FF835F", "#5AD2AE", "#77B5FF", "#DB9CFF"],
    },
  },
  {
    id: "onyx-teal",
    name: "Onyx Teal",
    category: "amoled",
    tone: { id: "Hitam & teal", en: "Black & teal" },
    colors: {
      canvas: "#000000",
      surface: "#031313",
      wash: "#062929",
      text: "#EEFFFF",
      muted: "#A5D2D2",
      border: "#1F6868",
      frame: "#000000",
      frameSurface: "#041B1B",
      frameText: "#F2FFFF",
      frameMuted: "#AFDEDE",
      accent: "#49DEDB",
      frameAccent: "#76ECE9",
      onAccent: "#032121",
      chart: ["#49DEDB", "#7AA7FF", "#FF99C0", "#F3C260"],
    },
  },
  {
    id: "dark-nebula",
    name: "Dark Nebula",
    category: "amoled",
    tone: { id: "Hitam & magenta", en: "Black & magenta" },
    colors: {
      canvas: "#000000",
      surface: "#120617",
      wash: "#2B0B35",
      text: "#FFF2FF",
      muted: "#D9B1DE",
      border: "#6A257C",
      frame: "#000000",
      frameSurface: "#19061F",
      frameText: "#FFF5FF",
      frameMuted: "#E0BBE5",
      accent: "#F070F5",
      frameAccent: "#FA96FF",
      onAccent: "#2E0632",
      chart: ["#F070F5", "#5EE0C1", "#7DAFFF", "#FFC05B"],
    },
  },
  {
    id: "mono-minimalist",
    name: "Mono Minimalist",
    category: "amoled",
    tone: { id: "Hitam & putih", en: "Black & white" },
    colors: {
      canvas: "#000000",
      surface: "#0D0D0D",
      wash: "#202020",
      text: "#F7F7F7",
      muted: "#C6C6C6",
      border: "#555555",
      frame: "#000000",
      frameSurface: "#151515",
      frameText: "#FAFAFA",
      frameMuted: "#D0D0D0",
      accent: "#F0F0F0",
      frameAccent: "#FFFFFF",
      onAccent: "#171717",
      chart: ["#F0F0F0", "#AFAFAF", "#7D7D7D", "#595959"],
    },
  },
];

export function getThemeById(themeId: string): ThemeDef {
  return themes.find((theme) => theme.id === themeId)
    ?? themes.find((theme) => theme.id === DEFAULT_THEME_ID)
    ?? themes[0];
}
